### ISSUE TITLE
Doc: Document Python dependencies in the Quick Start Guide

### ISSUE THREAD

**Issue by Paebbels** [VLSI-EDA/PoC#41]
The [Quick Start Guide](http://poc-library.readthedocs.io/en/release/QuickStart.html) lists Python 3 as a dependency, but it misses a list of Package dependencies, which could be installed from PyPI.

**Work Items:**
- [ ] Check if the Quick Start Guide links to the full documentation.
- [ ] Check if the full documentation contains all Python dependencies.
- [ ] Add a hint how to fulfill all Python dependencies via `pip`.
- [ ] List Python dependencies for other flows:
  - [ ] Appveyor
  - [ ] ReadTheDocs
  - [ ] Travis-CI
- [x] Register PoC at [Requires.io](https://requires.io/) to check if Python dependencies are up-to-date.
