### ISSUE TITLE
PyInfra: Add tool support for Aldec Riviera-PRO

### ISSUE THREAD

**Issue by Paebbels** [VLSI-EDA/PoC#44]
Add simulator support for Aldec Riviera-PRO.

**Work Items:**
* Simulator layer
  * [ ] Derive `RivieraPROSimulator` module from `ModelSimSimulator` module
* ToolChain Abstraction Layer
  * [ ] Derive `RivieraPRO` from `ModelSimSimulator`
    * [ ] Implement VHDLLibraryTool abstraction (vlib)
    * [ ] Implement VHDLCompiler abstraction (vcom)
    * [ ] Implement VHDLSimulator abstraction (vsim)
    * [ ] Implement output filters for
      * [ ] VHDLLibraryTool - vlib
      * [ ] VHDLCompiler - vcom
      * [ ] VHDLSimulator - vsim
* Implement a new Riviera-PRO command in `PoC.py`
  * [ ] add a `rpro` command line command and handler
* Add Riviera-PRO pre-compile support in pre-compile scripts for:
  * [ ] Altera
  * [ ] Intel
  * [ ] Lattice
  * [ ] Xilinx ISE
  * [ ] Xilinx Vivado
